backend:
  name: git-gateway
  branch: main # atau master, sesuaikan dengan branch GitHub Anda

media_folder: "data" # Folder tempat file GeoJSON/JS akan diunggah
public_folder: "data"

collections:
  - name: "peta_data"
    label: "Data Spasial Peta"
    folder: "data" # Target folder di repo Anda
    create: true # Mengizinkan admin upload file baru
    delete: true # Mengizinkan admin menghapus file
    fields:
      - {label: "Judul Data", name: "title", widget: "string"}
      - {label: "File GeoJSON", name: "body", widget: "file"}
